spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: message